Locales['en'] = {
  -- Cloakroom
  ['cloakroom'] = 'garderoba',
  ['citizen_wear'] = 'civilna obleka',
  ['police_wear'] = 'policijska obleka',
  ['gilet_wear'] = 'reflektivna obleka',
  ['bullet_wear'] = 'neprebojen jopič',
  ['no_outfit'] = 'nobena uniforma vam ne ustreza',
  ['open_cloackroom'] = 'pritisnite ~INPUT_CONTEXT~ da spremenite ~y~clothes~s~.',
  -- Armory
  ['remove_object'] = 'umaknite predmet',
  ['deposit_object'] = 'odložite predmet',
  ['get_weapon'] = 'vzemite orožje iz orožarne',
  ['put_weapon'] = 'shranite orožje v orožarno',
  ['buy_weapons'] = 'kupite orožje',
  ['armory'] = 'orožarna',
  ['open_armory'] = 'kliknite ~INPUT_CONTEXT~ da dostopate do ~y~Armory~s~.',
  ['armory_owned'] = 'v lasti',
  ['armory_free'] = 'zastonj',
  ['armory_item'] = '$%s',
  ['armory_weapontitle'] = 'orožarna - kupite orožje',
  ['armory_componenttitle'] = 'orožarna - dodatki za orožje',
  ['armory_bought'] = 'kupili ste ~y~%s~s~ za ~r~$%s~s~',
  ['armory_money'] = 'ne morete si privoščiti tega orožja',
  ['armory_hascomponent'] = 'ta dodatek imate že uporabljen!',
  ['get_weapon_menu'] = 'orožarna - vzemite orožje',
  ['put_weapon_menu'] = 'orožarna - shranite orožje',
  -- Vehicles
  ['vehicle_menu'] = 'vozila',
  ['vehicle_blocked'] = 'vsi prostori za vozila so zasedeni ',
  ['garage_prompt'] = 'kliknite ~INPUT_CONTEXT~ da dostopate ~y~Vehicle Actions~s~.',
  ['garage_title'] = 'vehicle Actions',
  ['garage_stored'] = 'shranjena',
  ['garage_notstored'] = 'ni v garaži',
  ['garage_storing'] = 'poskušamo odstraniti vozilo, prepričajte se da ni igralcev okoli njega',
  ['garage_has_stored'] = 'vozilo se vam je shranilo v garažo',
  ['garage_has_notstored'] = 'v bližini nismo našli nobenega vozila v vaši lasti',
  ['garage_notavailable'] = 'vaše vozilo ni shranjeno v garaži.',
  ['garage_blocked'] = 'ni razpoložljivih mest za vozilo!',
  ['garage_empty'] = 'v garaži nimate nobenega vozila.',
  ['garage_released'] = 'vaše vozilo je bilo dano ven iz garaže.',
  ['garage_store_nearby'] = 'v bližini ni vozil.',
  ['garage_storeditem'] = 'odprite garažo',
  ['garage_storeitem'] = 'shranite vozilo v garažo',
  ['garage_buyitem'] = 'trgovina z vozili',
  ['helicopter_prompt'] = 'kliknite ~INPUT_CONTEXT~ da dostopate do ~y~Helicopter Actions~s~.',
  ['helicopter_notauthorized'] = 'nimate pooblastili za nakup helikopterja.',
  ['shop_item'] = '$%s',
  ['vehicleshop_title'] = 'trgovina z vozili',
  ['vehicleshop_confirm'] = 'ali hočete kupiti to vozilo?',
  ['vehicleshop_bought'] = 'kupili ste ~y~%s~s~ za ~r~$%s~s~',
  ['vehicleshop_money'] = 'ne morete si privoščiti vozila',
  ['vehicleshop_awaiting_model'] = 'to vozilo je trenutno ~g~DOWNLOADING & LOADING~s~ prosimo počakajte',
  ['confirm_no'] = 'ne',
  ['confirm_yes'] = 'da',
  -- Service
  ['service_max'] = 'ne morete začeti dela, največ policajev v delu: %s/%s',
  ['service_not'] = 'niste začeli dela! najprej se morate preobleči.',
  ['service_anonunce'] = 'informacije o delu',
  ['service_in'] = 'začeli ste delo, dobrodošli!',
  ['service_in_announce'] = 'policaj ~y~%s~s~ je začel delo!',
  ['service_out'] = 'končali ste delo.',
  ['service_out_announce'] = 'policaj ~y~%s~s~ je končal delo.',
  -- Action Menu
  ['citizen_interaction'] = 'komuniciranje s civilisti',
  ['vehicle_interaction'] = 'dostop do vozila',
  ['object_spawner'] = 'object Spawner',

  ['id_card'] = 'osebna kartica',
  ['search'] = 'preišči',
  ['handcuff'] = 'nadenite lisice / odstranite lisice',
  ['drag'] = 'pospremite',
  ['put_in_vehicle'] = 'dajte v vozilo',
  ['out_the_vehicle'] = 'izvlečite ven iz vozila',
  ['fine'] = 'vredu',
  ['unpaid_bills'] = 'upravljajte neplačane položnice',
  ['license_check'] = 'upravljajte vozniško',
  ['license_revoke'] = 'prekličite vozniško',
  ['license_revoked'] = 'vaša ~b~%s~s~ je bila ~y~revoked~s~!',
  ['licence_you_revoked'] = 'preklicali ste ~b~%s~s~ kae ~y~%s~s~',
  ['no_players_nearby'] = 'v bližini ni igralcev!',
  ['being_searched'] = 'trenutno ste ~y~searched~s~ prek ~b~Police~s~',
  -- Vehicle interaction
  ['vehicle_info'] = 'informacije o vozilu',
  ['pick_lock'] = 'vdrite v vozilo',
  ['vehicle_unlocked'] = 'vozilo ~g~Unlocked~s~',
  ['no_vehicles_nearby'] = 'v bližini ni vozil',
  ['impound'] = 'zasežite vozilo',
  ['impound_prompt'] = 'kliknite ~INPUT_CONTEXT~ da prekličete ~y~impound~s~',
  ['impound_canceled'] = 'preklicali ste zaseg vozila',
  ['impound_canceled_moved'] = 'zaseg se je preklical ker se je vozilo premaknilo',
  ['impound_successful'] = 'zasegli ste vozilo',
  ['search_database'] = 'informacije o vozilu',
  ['search_database_title'] = 'informacije o vozilu - poiščite prek registracije',
  ['search_database_error_invalid'] = 'ta registracijska številka ~r~not~s~ a ~y~valid~s~',
  ['search_database_error_not_found'] = 'ta ~y~registration number~s~ is ~r~not~s~ registrirana na vozilo!',
  ['search_database_found'] = 'vozilo je ~y~registered~s~ na ~b~%s~s~',
  -- Traffic interaction
  ['traffic_interaction'] = 'interakcijski promet',
  ['cone'] = 'stožec',
  ['barrier'] = 'blokada',
  ['spikestrips'] = 'spikestrips',+++++++++++++
  ['box'] = 'škatla',
  ['cash'] = 'škatla z denarjem',
  -- ID Card Menu
  ['name'] = 'ime: %s',
  ['job'] = 'služba: %s',
  ['sex'] = 'spol: %s',
  ['dob'] = 'datum rojstva: %s',
  ['height'] = 'višina: %s',
  ['id'] = 'ID: %s',
  ['bac'] = 'alkohola v krvi: %s',
  ['unknown'] = 'neznan',
  ['male'] = 'moški',
  ['female'] = 'ženska',
  -- Body Search Menu
  ['guns_label'] = '--- Pištole ---',
  ['inventory_label'] = '--- Inventar ---',
  ['license_label'] = ' --- Dovoljenja ---',
  ['confiscate'] = 'zaplenite %s',
  ['confiscate_weapon'] = 'zaplenite %s z %s metki',
  ['confiscate_inv'] = 'zaplenite %sx %s',
  ['confiscate_dirty'] = 'zaplenite umazan denar: <span style="color:red;">$%s</span>',
  ['you_confiscated'] = 'zaplenili ste ~y~%sx~s~ ~b~%s~s~ od ~b~%s~s~',
  ['got_confiscated'] = '~y~%sx~s~ ~b~%s~s~ so bile zaplenjene od ~y~%s~s~',
  ['you_confiscated_account'] = 'zaplenili ste ~g~$%s~s~ (%s) od ~b~%s~s~',
  ['got_confiscated_account'] = '~g~$%s~s~ (%s) je bilo zaplenjeno od ~y~%s~s~',
  ['you_confiscated_weapon'] = 'zaplenili ste ~b~%s~s~ od ~b~%s~s~ z ~o~%s~s~ metki',
  ['got_confiscated_weapon'] = 'vaš ~b~%s~s~ z ~o~%s~s~ je bil zapljenjen od ~y~%s~s~',
  ['traffic_offense'] = 'prometni prekršek',
  ['minor_offense'] = 'manjši prekršek',
  ['average_offense'] = 'normalni prekršek',
  ['major_offense'] = 'večji prekršek',
  ['fine_total'] = 'denarna kazen: %s',
  -- Vehicle Info Menu
  ['plate'] = 'registracija: %s',
  ['owner_unknown'] = 'lastnik: neznan',
  ['owner'] = 'lastnik: %s',
  -- Boss Menu
  ['open_bossmenu'] = 'kliknite ~INPUT_CONTEXT~ da odprete menu',
  ['quantity_invalid'] = 'neveljavna količina',
  ['have_withdrawn'] = 'dvignili ste ~y~%sx~s~ ~b~%s~s~',
  ['have_deposited'] = 'položili ste ~y~%sx~s~ ~b~%s~s~',
  ['quantity'] = 'količina',
  ['inventory'] = 'inventar',
  ['police_stock'] = 'policijska zaloga',
  -- Misc
  ['remove_prop'] = 'kliknite ~INPUT_CONTEXT~ da izbrišete objekt',
  ['map_blip'] = 'policijska postaja',
  ['unrestrained_timer'] = 'čutite, da vam lisice počasi izgubljajo oprijem in bledijo.',
  -- Notifications
  ['alert_police'] = 'policijski alarm',
  ['phone_police'] = 'policija',
}
